version: "3.1"

services:
  database:
    hostname: authentication_service_pgdb_host
    container_name: authentication_service_pgdb
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication_service_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - app

volumes:
  local_pgdata:
  pgadmin-data:
networks:
  app: