apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-service-ns
  labels:
    app: auth-service
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: auth-service